### ISSUE TITLE
Delegator.run is not an attribute

### ISSUE THREAD

**Issue by apoorvagnihotri** [hugobast/delegator#4]
While using delegator we encounter the following error. Could you please help us out?

Code run..

```python
# Check our running processes to be less than max., else sleep
    while len(delegator.run(f'squeue -u {username}').out.split("\n")) > MAX_NUM_MY_JOBS + 2:
        time.sleep(DELAY_NUM_JOBS_EXCEEDED)
```

Error Recieved

```python
Traceback (most recent call last): 
  File "lasso_caller.py", line 97, in <module> 
    call_python(i, j) 
  File "lasso_caller.py", line 34, in call_python 
    while len(delegator.run(f'squeue -u {username}').out.split("\n")) > MAX_NUM_MY_JOBS + 2: 
AttributeError: module 'delegator' has no attribute 'run'
```

**Comment by apoorvagnihotri** [comment]
I seem to have confused this repository with [`delegator.py`](https://github.com/amitt001/delegator.py). I am sorry for the confusion!
